### ISSUE TITLE
Scrollable menu content

### ISSUE THREAD

**Issue by billdami** [tsubik/ember-side-menu#10]
In our app, we are using ember-side-menu and it contains a scrollable content area which is absolutely positioned with `overflow-y: scroll` (we have a header bar above it which we dont want to scroll). This works well in mouse-based environments, but scrolling within the ember-side-menu content seems to be completely disabled on touch devices.

It appears that the cause of this is specifically line 140 in addon/components/side-menu.js, where `event.preventDefault();` is called within the touchMove event listener. When this line is removed, scrolling works fine on touch devices, and it doesn't seem to negatively affect the functionality of the menu itself.

Is this behavior of disabling scrolling within the menu intentional, and if so, why? And/or is there any other way to enable scrolling without having to remove the `event.preventDefault();`?

**Comment by tsubik** [comment]
@billdami thanks for opening this issue. I will check this behavior shortly. I agree that menu content scroll shouldn't be disabled, I believe it should be blocked during the opening or closing transition.

**Comment by billdami** [comment]
@tsubik Ah I see, yeah that makes more sense.

**Comment by Charizard** [comment]
@billdami Does removing the line fix the scroll issue for you? It doesn't seem to work for me. Also, did you use any workaround for this?

**Comment by Charizard** [comment]
@tsubik @billdami I found a workaround by wrapping the `event.preventDefault();` in a condition.
```
            if (this._isTouchWithin(event, get(this, "slightlyOpenWidth"))) {
                event.preventDefault();
            }
```
Open / Close in touch devices working, and scroll up / down working fine. Let me know if this is correct so I can open up an MR.

**Comment by tsubik** [comment]
Hey @Charizard @billdami I've pushed some changes into master branch. I'm not sure what was the resoning to have `preventDefault` there, I've removed it. Ideal behavior is to have scroll blocked everywhere but not inside the menu itself when is open/opening. You can test if that works for you, and if it's :+1: then I will push new version into npm.

**Comment by Charizard** [comment]
The scroll is working now. But, when I try to scroll up/down (in touch devices) the menu is trying to close/open. I have to be really careful while scrolling for this to not happen. In other words it doesn't feel natural.

> Ideal behavior is to have scroll blocked everywhere but not inside the menu itself when is open/opening.

Yeah, I guess you are right.

Let me know if you need some help!!

**Comment by tsubik** [comment]
Thanks I will try to fix that.

**Comment by tsubik** [comment]
@Charizard @billdami done some initial work on master to allow only menu scroll or opening to happen at the same moment.

**Comment by tsubik** [comment]
I hope fixed with latest changes in version https://github.com/tsubik/ember-side-menu/releases/tag/v0.0.14. Feel free to reopen if not.
