### ISSUE TITLE
Can this be decoupled from Bootstrap better?

### ISSUE THREAD

**Issue by Hucxley** [tsubik/ember-side-menu#13]
Is it enough to remove the ul and li style from the scss, because I use Semantic UI for the rest of the page that I'm using your side menu on.  Is the addon easily framework agnostic?  I know many people use Bootstrap, but many don't, and there aren't as many options out there for menu systems that give you the function without also forcing a style framework.

**Comment by tsubik** [comment]
This plugin is not coupled with Bootstrap. Maybe the example in readme is taken from one of my "bootstrapped" apps, but look at dummy app in this repository https://tsubik.com/ember-side-menu/. That's not bootstrap, you can add any content you want into side-menu and shape it as you like.

**Comment by Hucxley** [comment]
Yep, you're correct.  I've spent quite a bit of time restyling it.  Sorry to have jumped the gun.  Do you mind telling me how to use the parameters so I can switch it to the right side and adjust the size?  70% is a little bit large on a desktop, so I wanted to change the size with media queries.  You can send it as a message instead, if that's better for you.

**Comment by tsubik** [comment]
Base styles you should still import as it states in readme, then basic things like position and width you can set via parameters https://github.com/tsubik/ember-side-menu#parameters.
