### ISSUE TITLE
Feature: multiple side menus

### ISSUE THREAD

**Issue by Owlman145** [tsubik/ember-side-menu#15]
The ability to have different side-menus, with different toggles, would be great. While I made my own modifications to it on my app to do this, it is not generalized.

**Comment by tsubik** [comment]
I agree :+1: I wanted to add that feature long time ago, but constantly cannot find time to do so :/

**Comment by erichonkanen** [comment]
hey any ideas on how to implement this? I basically have to figure out how to do it!

**Comment by Owlman145** [comment]
I have an hackish implementation for it (see link), where I just extend the current plugin with my app. I haven't gotten around to making a proper fork.

https://gist.github.com/Owlman145/54ea38b1d2d1e2cdb26426b55663a341
File location in my app: 
 - {app-dir}/app/services/side-menu.js 
 - {app-dir}/pods/components/side-menu/component.js
If not using pods, move and rename


 component.js to {app-dir}/components/side-menu.js

**Comment by erichonkanen** [comment]
ok thanks I'll check that out.. so looks like you can `{{#side-menu name='menu-1'}}` etc?

separately, have you had any issues with the content-backdrop and clicks going behind it? when I click on it to have the menu close it is clicking on whatever is behind the backdrop for me.. not sure if it's a problem with my implementation or something else (I tried playing w/pointer-events)

**Comment by erichonkanen** [comment]
@Owlman145 thanks for that, I added the changes to my project but for some reason the sidemenu was rendering out of frame now so I backed it out. May try again later. What I'm wondering is if it's possible to use a set up like I have below to effectively dynamically send content into the menu/set the side etc and open/close it using ember-elsewhere? For a single menu this works fine but not sure which direction to go w/needing to support a menu that comes from right and may contain a few different things on different pages...

any ideas appreciated!

Here is how I have it set up:
rendered in `app/templates/application.hbs`
```
{{#from-elsewhere name='side-menu' as |elsewhere|}}
  {{#if elsewhere}}
    {{#side-menu
        side=(or elsewhere.side 'left')
        width=(or elsewhere.width '310px')
    }}
      {{elsewhere.component}}
    {{/side-menu}}

    {{content-backdrop}}
  {{/if}}
{{/from-elsewhere}}
```
navigation component
```
  <div class="global-navigation global-navigation--mobile">
    <button
      class="global-navigation__button global-navigation__main-menu"
      data-test-main-menu-button=true
      {{action 'showSideMenu'}}
    >
      {{font-icon 'bars'}}
    </button>
{{/if}}

{{#if (not media.isXl)}}
  {{to-elsewhere
    named='side-menu'
    send=(hash
      component=(component 'to-elsewhere/sidemenu/mobile-navigation')
    )
  }}
{{/if}}
```
then I open it via the navigation component
```
  actions: {
    showSideMenu() {
      return get(this, 'sideMenu').open();
    },
  },
```

**Comment by erichonkanen** [comment]
@Owlman145 I was able to get it work based on your implementation, the only thing that's missing is how to handle the `{{content-backdrop}}` `close()` event properly.. for now in my project I just explicitly close both menus but maybe we can think of a better solution and we can update this library to support multiple menus so we don't have to do it in our apps?

@tsubik any reason why content-backdrop isn't just rendered automatically versus having to explicitly define it? 

Let's add this feature!
