### ISSUE TITLE
Ember deprecations

### ISSUE THREAD

**Issue by arthurvasconcelos** [tsubik/ember-side-menu#2]
I am receiving this deprecation alerts when the component is instantiated.

![screenshot from 2016-07-22 13 36 12](https://cloud.githubusercontent.com/assets/1286768/17064140/674ec8f6-5011-11e6-9638-94bd2ca94041.png)

**Comment by tsubik** [comment]
Hey @arthurvasconcelos, I cannot reproduce this. Are you using the latest 0.0.6 version of the plugin?

**Comment by arthurvasconcelos** [comment]
@tsubik yes i was using the latest. I'm sorry for that, this issue is no related with your lib. In further tests I've checked that other lib was causing this... The only real bug that I found is in the issue #3. Great lib! Congratz.

**Comment by tsubik** [comment]
Ok. No problem.
