### ISSUE TITLE
Cannot read property 'addEventListener' of undefined

### ISSUE THREAD

**Issue by arthurvasconcelos** [tsubik/ember-side-menu#3]
Just when I try swipe to open the menu I receive this error.

![screenshot from 2016-07-22 13 36 38](https://cloud.githubusercontent.com/assets/1286768/17064179/a1cbcb32-5011-11e6-913c-c352e0660103.png)

**side-menu.js:140**
```js
rootNode.addEventListener("touchmove", throttledOnTouchMove);
rootNode.addEventListener("touchend", onTouchEnd);
```

**Comment by tsubik** [comment]
Hey @arthurvasconcelos, please check if the newest version is free from this error.

**Comment by tsubik** [comment]
I'm closing. If this is still the issue please feel to reopen.
