### ISSUE TITLE
ember-side-menu breaks fastboot render

### ISSUE THREAD

**Issue by bakerac4** [tsubik/ember-side-menu#8]
We don't have access to jQuery inside of Fastboot.
```
 TypeError: $ is not a function
    at [object Object].disableScroll (/Users/adambaker/Development/project/projectname/dist/fastboot/vendor.js:100110:29)
```

which leads me to 

```
var $rootNode = $(get(this, "rootNodeSelector"));
```
https://ember-fastboot.com/docs/addon-author-guide

There are a few different ways to solve this, but one is to move the definition of the observer into the didInsertElement

**Comment by tsubik** [comment]
Thanks for reporting this and hints @bakerac4 :+1:
